name: calendar_timeline
description: A horizontal date picker that takes up little screen space, so we can always have it visible, and that facilitates use with one hand.
version: 0.6.1
homepage: https://github.com/ikicodedev/calendar_timeline

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.1.6
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
