name: calendar_timeline
description: A horizontal date picker that takes up little screen space, so we
  can always have it visible, and that facilitates use with one hand.
version: 1.1.3
homepage: https://github.com/muhammadtalhasultan/calendar_timeline

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  scrollable_positioned_list: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
